
name: Build .NET6 Web Apps

on:
  workflow_call:
    inputs:
      APP:
        required: true
        type: string
      SLOT:
        required: true
        type: string
      DEPLOY_ENV:
        required: true
        type: string
      BUILD_CONFIG:
        required: true
        type: string
      BUILD_PROJECT:
        required: true
        type: string
    secrets:
      SSH_KEY:
        required: true

jobs:
  build-dot-net6:
    runs-on: windows-latest

    steps:
      - name: Checkout repo and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Restore NuGet packages.
        run: dotnet restore --source https://api.nuget.org/v3/index.json

      - name: Publish the project.
        run: dotnet publish ${{inputs.BUILD_PROJECT}} -c ${{inputs.BUILD_CONFIG}} -o ${{env.DOTNET_ROOT}}/myapp

      - name: Copy environment specific files in place.
        uses: SurePassId/copy-web-env-files@main
        with:
          deployment-environment: ${{inputs.DEPLOY_ENV}}
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Upload build artifact app-${{inputs.APP}}-${{inputs.SLOT}} for deployment jobs.
        uses: actions/upload-artifact@v2
        with:
          name: app-${{inputs.APP}}-${{inputs.SLOT}}
          path: ${{env.DOTNET_ROOT}}/myapp