# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy to Azure App Service

on:
  workflow_call:
    inputs:
      APP:
        required: true
        type: string
      SLOT:
        required: true
        type: string
      DEPLOY_ENV:
        required: true
        type: string
      REGION:
        required: true
        type: string
    secrets:
      PUBLISH_PROFILE:
        required: true

jobs:
  deploy-to-app-service:
    #runs-on: windows-latest
    runs-on: [self-hosted, windows-build-vm]
    environment:
      name: app-${{inputs.APP}}-${{inputs.DEPLOY_ENV}}-${{inputs.REGION}}/${{inputs.SLOT}}
      url: ${{steps.deploy-to-webapp.outputs.webapp-url}}
      
    steps:
      - name: Download artifact app-${{inputs.APP}}-${{inputs.SLOT}} from the build job
        uses: actions/download-artifact@v3
        with:
          name: app-${{inputs.APP}}-${{inputs.SLOT}}
          path: ./deplotment-package

      - name: Deploy to Azure App Service app-${{inputs.APP}}-${{inputs.DEPLOY_ENV}}-${{inputs.REGION}}/${{inputs.SLOT}}
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-${{inputs.APP}}-${{inputs.DEPLOY_ENV}}-${{inputs.REGION}}
          slot-name: ${{inputs.SLOT}}
          publish-profile: ${{secrets.PUBLISH_PROFILE}}
          package: ./deplotment-package
          
